import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import axios from 'axios'

import ProductThumbnail from '@/components/ProductThumbnail'
import Carousel from '@/components/images/Carousel'
import Product from '@/components/Product'

export default function Home({ patterns }:any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Product data={patterns[0]}/>
      <Carousel images={patterns[0].attributes.images.data}/>
      {patterns.map((pattern:any, i:number) => {
          return (
            <ProductThumbnail key={i} data={pattern}/>
          )
        })}
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const patterns = await axios.get(
    `${process.env.NEXT_PUBLIC_STRAPI_URL}api/patterns?populate=*`
  )
  return {
    props: {
      patterns: patterns?.data.data ?? [],
    }
  }
}
